env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - cleanjs

parser: 'babel-eslint'
parserOptions:
  sourceType: module

rules:
  import/no-commonjs:
    - off # nodejs does not have this
  fp/no-unused-expression:
    - off # false positives
  fp/no-mutation:
    - error
    - commonjs: true # allow export statement
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
