exports.coins = [
    ['ANS'     , 'Antshares'       ] ,
    ['BCN'     , 'Bytecoin'        ] ,
    ['BTC'     , 'Bitcoin'         ] ,
    ['BTS'     , 'Bitshares'       ] ,
    ['DASH'    , 'Dash'            ] ,
    ['DCR'     , 'Antshares'       ] ,
    ['DGB'     , 'Digibyte'        ] ,
    ['DOGE'    , 'Dogecoin'        ] ,
    ['EOS'     , 'Eos'             ] ,
    ['ETC'     , 'EthereumClassic' ] ,
    ['ETH'     , 'Ethereum'        ] ,
    ['GNO'     , 'Gnosis'          ] ,
    ['GNT'     , 'Golem'           ] ,
    ['IOT'     , 'Iota'            ] ,
    ['ICN'     , 'Iconomi'         ] ,
    ['LTC'     , 'Litecoin'        ] ,
    ['MTL'     , 'Metal'           ] ,
    ['PPC'     , 'Peercoin'        ] ,
    ['QTUM'    , 'Qtum'            ] ,
    ['SC'      , 'Siacoin'         ] ,
    ['SNT'     , 'Status'          ] ,
    ['STRAT'   , 'Stratis'         ] ,
    ['STEEM'   , 'Steem'           ] ,
    ['VIA'     , 'Viacoin'         ] ,
    ['WAVES'   , 'Waves'           ] ,
    ['XEM'     , 'Nem'             ] ,
    ['XMP'     , 'Primecoin'       ] ,
    ['XMR'     , 'Monero'          ] ,
    ['XRP'     , 'Ripple'          ] ,
    ['ZEC'     , 'Zcash'           ]
]
